# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: 'npm'
    directories:
      - '/.'
      - '/tools/code-style'
      - '/tools/docs-gen'
      - '/tools/schema-downloader'
    schedule:
      interval: 'weekly'
      day: 'saturday'
    allow:
      - dependency-type: 'all'
    versioning-strategy: 'auto'
    labels: [ 'dependencies' ]
    commit-message:
      prefix: 'chore'  ## prefix maximum string length of 15
      include: 'scope'
    open-pull-requests-limit: 999
    ignore:
      - dependency-name: "@types/node"
        # version is like `ts.X.Y` -- need to maintain manually
    groups:
      eslint:
        patterns:
          - 'eslint'
          - '@eslint/*'
          - '*-eslint'
          - 'eslint-*'
          - '@types/eslint'
          - '@types/eslint-*'
          - '@types/*-eslint'
          - '@eslint-community/*'
          - '@typescript-eslint/*'
      spdx:
        patterns:
          - 'spdx-*'
          - '@types/spdx-*'
      ajv:
        patterns:
          - 'ajv'
          - 'ajv-*'
      typedoc:
        patterns:
          - 'typedoc'
          - 'typedoc-*'
          - '@microsoft/tsdoc'
          - '@microsoft/tsdoc-*'
      typescript:
        patterns:
          - 'typescript'
          - '@types/*'
          - 'ts-loader'
          - 'tslib'
      webpack:
        patterns:
          - 'webpack'
          - 'webpack-*'
          - '@webpack-cli/*'
          - '@webassemblyjs/*'
          - 'browserslist'
          - 'caniuse-*'
          - 'ts-loader'
      mocha:
        patterns:
          - 'mocha'
          - '@types/mocha'
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'saturday'
    labels: [ 'dependencies' ]
    commit-message:
      prefix: 'chore'   ## prefix maximum string length of 15
      include: 'scope'
    open-pull-requests-limit: 999
