export enum ExternalReferenceType {
    VCS = "vcs",
    IssueTracker = "issue-tracker",
    Website = "website",
    Advisories = "advisories",
    BOM = "bom",
    MailingList = "mailing-list",
    Social = "social",
    Chat = "chat",
    Documentation = "documentation",
    Support = "support",
    Distribution = "distribution",
    License = "license",
    BuildMeta = "build-meta",
    BuildSystem = "build-system",
    ReleaseNotes = "release-notes",
    Other = "other",
}
