/*!
This file is part of CycloneDX JavaScript Library.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

SPDX-License-Identifier: Apache-2.0
Copyright (c) OWASP Foundation. All Rights Reserved.
*/

import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const PROJECT_ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..')

const schema = JSON.parse(readFileSync(join(PROJECT_ROOT, 'res', 'schema', 'spdx.SNAPSHOT.schema.json')))

const header = readFileSync(join(PROJECT_ROOT, '.license-header.js'))

writeFileSync(join(PROJECT_ROOT, 'src', 'spdx_specenum.ts'), `${header}
/**
 * The following symbols are _internal_ and are not intended to be exported/published.
 * @privateRemarks
 * This file was generated by \`../tools/spdx-specenum-converter/convert.js\` during a pre-build phase
 */
/* eslint-disable max-lines -- generated as-is */

import type { SpdxId } from './spdx'

/**
 * List of well-known SPDX IDs - ${schema['$comment']}
 *
 * @remarks
 * Based on file \`../res/schema/spdx.SNAPSHOT.schema.json\`
 */
export const LIST: readonly SpdxId[] = Object.freeze(${JSON.stringify(schema.enum, null, 2)})
`)
